#!/bin/sh
if [ $(uname -s) = Darwin ]; then
	MAFIA_DIR="${HOME}/Library/Application Support/KoLmafia"
else
	MAFIA_DIR="${HOME}/.kolmafia"
fi
ROOT_DIR=${MAFIA_DIR}/program
URL=http://ci.kolmafia.us/job/Kolmafia/lastSuccessfulBuild/artifact/dist/
COMMITURL=http://ci.kolmafia.us/job/Kolmafia/lastSuccessfulBuild/changes

# Check for a java installation
command -v java >/dev/null 2>&1 || {
	printf "\033[41m\033[30mERROR\033[0m -- You do not have java installed, or it is not in your \$PATH.\n"
	printf "Please install it using your system's package manager.  The following command\n"
	printf "lines are for common systems:\n"
	printf "OSX:            \033[7mbrew install java\033[0m\n"
	printf "Ubuntu:         \033[7mapt-get install openjdk-7-jdk\033[0m\n"
	printf "Debian:         \033[7mapt-get install java\033[0m\n"
	printf "Fedora <22:     \033[7myum install java\033[0m\n"
	printf "Fedora >=22:    \033[7mdnf install java\033[0m\n"
	printf "Most BSDs:      \033[7mpkg install java\033[0m\n"
	exit 1
}

# Pretty colors
yes(){
	printf "\033[32m\033[1myes\033[0m\n"
}
no(){
	printf "\033[31m\033[1mno\033[0m\n"
}
#actually done
finished(){
	printf "\033[35m\033[1mdone!\033[0m\n"
}
check(){
	printf "\033[36m\033[1mChecking\033[0m if \033[33m\033[1m$@\033[0m..."
}


# It's probably safe to just assume that if the dirs are there, the app is
# installed.  Yes, someone could tinker with this, but this is PROBABLY
# reasonable.
check "\033[0m\033[35m\033[4mKoLMafia\033[0m\033[1m\033[33m is installed"
if [ -d $MAFIA_DIR ]; then
	yes
	mafia_install=true
else
	no
	mafia_install=false
fi

check "Mafia autoupdater is installed"
if [ -d $ROOT_DIR ]; then
	yes
	new_install=false
else
	no
	new_install=true
fi

if $new_install; then
	mkdir -p $ROOT_DIR
fi

if $new_install; then
	printf "\033[36m\033[1mDownloading\033[0m \033[35m\033[4mKoLMafia\033[0m for the \033[33m\033[1mfirst time\033[0m..."
else
	check "a new version is available"
fi

commitmsg=$(curl $COMMITURL 2>/dev/null | sed -n 14p | cut -c 13- | tr -d "\n")
getcommit() {
	printf "\033[32mRevision\033[0m\033[34m \033[31m#${version_number},\033[0m\033[34m \033[4m\"${commitmsg}\"\033[0m\n"
}

# Short explanation: fetch builds.kolmafia.us, get line 11 (which is the
# one with the download links), strip away everything before the URL
# (chop off the first 427 chars), then chop everything after the URL (get
# only the first 18 chars).
download=$URL/$(curl $URL 2>/dev/null|sed -n 11p|cut -c 427-|cut -c 1-18)
version_number=$(echo $download|cut -c 80-|cut -c 1-5)

if $new_install; then
	curl $download > $ROOT_DIR/$version_number 2>/dev/null
	finished
else
	if [ -f $ROOT_DIR/$version_number ]; then
		printf "\033[35m\033[1mKoLMafia is up to date!\033[0m\n"
	else
		yes
		printf "\033[36m\033[1mDownloading\033[0m the \033[33m\033[1mlatest version of\033[0m \033[35m\033[4mKoLMafia\033[0m..."
		rm -f $ROOT_DIR/*
		curl $download > $ROOT_DIR/$version_number 2>/dev/null
		finished
	fi
fi
getcommit
echo
printf "\033[36m\033[1mRunning\033[0m \033[35m\033[4mKoLMafia\033[0m.\n"
java -jar $ROOT_DIR/$version_number $@
